# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'UI/AddNoticePageUI.ui'
#
# Created by: PyQt5 UI code generator 5.15.2
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_AddNotice(object):
    def setupUi(self, AddNotice):
        AddNotice.setObjectName("AddNotice")
        AddNotice.resize(800, 600)
        AddNotice.setMinimumSize(QtCore.QSize(800, 600))
        font = QtGui.QFont()
        font.setFamily("Palatino Linotype")
        font.setPointSize(18)
        AddNotice.setFont(font)
        self.horizontalLayoutWidget = QtWidgets.QWidget(AddNotice)
        self.horizontalLayoutWidget.setGeometry(QtCore.QRect(190, 220, 451, 121))
        self.horizontalLayoutWidget.setObjectName("horizontalLayoutWidget")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.horizontalLayoutWidget)
        self.horizontalLayout.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.verticalLayout = QtWidgets.QVBoxLayout()
        self.verticalLayout.setObjectName("verticalLayout")
        self.lbl_date = QtWidgets.QLabel(self.horizontalLayoutWidget)
        self.lbl_date.setObjectName("lbl_date")
        self.verticalLayout.addWidget(self.lbl_date)
        self.lbl_notice = QtWidgets.QLabel(self.horizontalLayoutWidget)
        self.lbl_notice.setObjectName("lbl_notice")
        self.verticalLayout.addWidget(self.lbl_notice)
        self.horizontalLayout.addLayout(self.verticalLayout)
        self.verticalLayout_2 = QtWidgets.QVBoxLayout()
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.txt_date = QtWidgets.QLineEdit(self.horizontalLayoutWidget)
        self.txt_date.setObjectName("txt_date")
        self.verticalLayout_2.addWidget(self.txt_date)
        self.txt_notice = QtWidgets.QLineEdit(self.horizontalLayoutWidget)
        self.txt_notice.setObjectName("txt_notice")
        self.verticalLayout_2.addWidget(self.txt_notice)
        self.horizontalLayout.addLayout(self.verticalLayout_2)
        self.lbl_title = QtWidgets.QLabel(AddNotice)
        self.lbl_title.setGeometry(QtCore.QRect(240, 10, 361, 80))
        font = QtGui.QFont()
        font.setFamily("Palatino Linotype")
        font.setPointSize(35)
        font.setBold(True)
        font.setWeight(75)
        self.lbl_title.setFont(font)
        self.lbl_title.setStyleSheet("color: rgb(85, 170, 255);")
        self.lbl_title.setObjectName("lbl_title")
        self.btn_back = QtWidgets.QPushButton(AddNotice)
        self.btn_back.setGeometry(QtCore.QRect(400, 520, 160, 55))
        font = QtGui.QFont()
        font.setFamily("Palatino Linotype")
        font.setPointSize(18)
        font.setUnderline(True)
        self.btn_back.setFont(font)
        self.btn_back.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.btn_back.setStyleSheet("border: 1px solid black;\n"
"color: rgb(85, 170, 255);")
        self.btn_back.setObjectName("btn_back")
        self.btn_addNotice = QtWidgets.QPushButton(AddNotice)
        self.btn_addNotice.setGeometry(QtCore.QRect(580, 520, 191, 55))
        font = QtGui.QFont()
        font.setFamily("Palatino Linotype")
        font.setPointSize(18)
        font.setUnderline(True)
        self.btn_addNotice.setFont(font)
        self.btn_addNotice.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.btn_addNotice.setStyleSheet("border: 1px solid black;\n"
"color: rgb(85, 170, 255);")
        self.btn_addNotice.setObjectName("btn_addNotice")

        self.retranslateUi(AddNotice)
        QtCore.QMetaObject.connectSlotsByName(AddNotice)

    def retranslateUi(self, AddNotice):
        _translate = QtCore.QCoreApplication.translate
        AddNotice.setWindowTitle(_translate("AddNotice", "Term Spors Complex"))
        self.lbl_date.setText(_translate("AddNotice", "Date:"))
        self.lbl_notice.setText(_translate("AddNotice", "Notice:"))
        self.lbl_title.setText(_translate("AddNotice", "Add a Notice"))
        self.btn_back.setText(_translate("AddNotice", "Back"))
        self.btn_addNotice.setText(_translate("AddNotice", "Add Notice"))
