# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'UI/AdminMainPageUI.ui'
#
# Created by: PyQt5 UI code generator 5.15.2
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_AdminMain(object):
    def setupUi(self, AdminMain):
        AdminMain.setObjectName("AdminMain")
        AdminMain.resize(800, 600)
        AdminMain.setMinimumSize(QtCore.QSize(800, 600))
        AdminMain.setMaximumSize(QtCore.QSize(800, 600))
        font = QtGui.QFont()
        font.setFamily("Palatino Linotype")
        font.setPointSize(18)
        AdminMain.setFont(font)
        AdminMain.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.lbl_title = QtWidgets.QLabel(AdminMain)
        self.lbl_title.setGeometry(QtCore.QRect(170, 10, 521, 80))
        font = QtGui.QFont()
        font.setFamily("Palatino Linotype")
        font.setPointSize(35)
        font.setBold(True)
        font.setWeight(75)
        self.lbl_title.setFont(font)
        self.lbl_title.setStyleSheet("color: #9E9E9E;")
        self.lbl_title.setObjectName("lbl_title")
        self.btn_deleteLesson = QtWidgets.QPushButton(AdminMain)
        self.btn_deleteLesson.setGeometry(QtCore.QRect(30, 525, 180, 50))
        font = QtGui.QFont()
        font.setFamily("Palatino Linotype")
        font.setPointSize(16)
        font.setUnderline(False)
        self.btn_deleteLesson.setFont(font)
        self.btn_deleteLesson.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.btn_deleteLesson.setStyleSheet("QPushButton{\n"
"    border: 2px solid #9E9E9E;\n"
"    border-radius: 15px;\n"
"    background-color: QLinearGradient( x1: 0, y1: 0, x2: 0, y2: 1, stop: 0 #88d, stop: 0.1 #99e, stop: 0.49 #77c, stop: 0.5 #66b, stop: 1 #77c);\n"
"    color: #FFFFFF;\n"
"}\n"
"QPushButton:hover{\n"
"    color: #9E9E9E;\n"
"    background-color: #5a5a5a;\n"
"}\n"
"QPushButton:pressed{\n"
"    color: #9c2219;\n"
"}\n"
"QPushButton:checked{\n"
"    color: #2c998e;\n"
"}")
        self.btn_deleteLesson.setObjectName("btn_deleteLesson")
        self.btn_addLesson = QtWidgets.QPushButton(AdminMain)
        self.btn_addLesson.setGeometry(QtCore.QRect(590, 525, 180, 50))
        font = QtGui.QFont()
        font.setFamily("Palatino Linotype")
        font.setPointSize(16)
        font.setUnderline(False)
        self.btn_addLesson.setFont(font)
        self.btn_addLesson.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.btn_addLesson.setStyleSheet("QPushButton{\n"
"    border: 2px solid #9E9E9E;\n"
"    border-radius: 15px;\n"
"    background-color: QLinearGradient( x1: 0, y1: 0, x2: 0, y2: 1, stop: 0 #88d, stop: 0.1 #99e, stop: 0.49 #77c, stop: 0.5 #66b, stop: 1 #77c);\n"
"    color: #FFFFFF;\n"
"}\n"
"QPushButton:hover{\n"
"    color: #9E9E9E;\n"
"    background-color: #5a5a5a;\n"
"}\n"
"QPushButton:pressed{\n"
"    color: #9c2219;\n"
"}\n"
"QPushButton:checked{\n"
"    color: #2c998e;\n"
"}")
        self.btn_addLesson.setObjectName("btn_addLesson")
        self.label = QtWidgets.QLabel(AdminMain)
        self.label.setGeometry(QtCore.QRect(220, 90, 371, 81))
        self.label.setObjectName("label")
        self.btn_addNotice = QtWidgets.QPushButton(AdminMain)
        self.btn_addNotice.setGeometry(QtCore.QRect(400, 525, 180, 50))
        font = QtGui.QFont()
        font.setFamily("Palatino Linotype")
        font.setPointSize(16)
        font.setUnderline(False)
        self.btn_addNotice.setFont(font)
        self.btn_addNotice.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.btn_addNotice.setStyleSheet("QPushButton{\n"
"    border: 2px solid #9E9E9E;\n"
"    border-radius: 15px;\n"
"    background-color: QLinearGradient( x1: 0, y1: 0, x2: 0, y2: 1, stop: 0 #88d, stop: 0.1 #99e, stop: 0.49 #77c, stop: 0.5 #66b, stop: 1 #77c);\n"
"    color: #FFFFFF;\n"
"}\n"
"QPushButton:hover{\n"
"    color: #9E9E9E;\n"
"    background-color: #5a5a5a;\n"
"}\n"
"QPushButton:pressed{\n"
"    color: #9c2219;\n"
"}\n"
"QPushButton:checked{\n"
"    color: #2c998e;\n"
"}")
        self.btn_addNotice.setObjectName("btn_addNotice")
        self.tableWidget = QtWidgets.QTableWidget(AdminMain)
        self.tableWidget.setGeometry(QtCore.QRect(30, 170, 741, 331))
        font = QtGui.QFont()
        font.setFamily("Palatino Linotype")
        font.setPointSize(14)
        self.tableWidget.setFont(font)
        self.tableWidget.setStyleSheet("")
        self.tableWidget.setFrameShape(QtWidgets.QFrame.Panel)
        self.tableWidget.setTabKeyNavigation(True)
        self.tableWidget.setAlternatingRowColors(True)
        self.tableWidget.setGridStyle(QtCore.Qt.SolidLine)
        self.tableWidget.setRowCount(0)
        self.tableWidget.setColumnCount(0)
        self.tableWidget.setObjectName("tableWidget")
        self.tableWidget.horizontalHeader().setVisible(True)
        self.tableWidget.verticalHeader().setVisible(False)

        self.retranslateUi(AdminMain)
        QtCore.QMetaObject.connectSlotsByName(AdminMain)

    def retranslateUi(self, AdminMain):
        _translate = QtCore.QCoreApplication.translate
        AdminMain.setWindowTitle(_translate("AdminMain", "Term Spors Complex"))
        self.lbl_title.setText(_translate("AdminMain", "Admin Main Page"))
        self.btn_deleteLesson.setText(_translate("AdminMain", "Delete Lesson"))
        self.btn_addLesson.setText(_translate("AdminMain", "Add Lesson"))
        self.label.setText(_translate("AdminMain", "Upcoming Class Schedules"))
        self.btn_addNotice.setText(_translate("AdminMain", "Add Notice"))
