# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'UI/AdminMainPageUI.ui'
#
# Created by: PyQt5 UI code generator 5.15.2
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_AdminMain(object):
    def setupUi(self, AdminMain):
        AdminMain.setObjectName("AdminMain")
        AdminMain.resize(800, 600)
        AdminMain.setMinimumSize(QtCore.QSize(800, 600))
        font = QtGui.QFont()
        font.setFamily("Palatino Linotype")
        font.setPointSize(18)
        AdminMain.setFont(font)
        self.lbl_title = QtWidgets.QLabel(AdminMain)
        self.lbl_title.setGeometry(QtCore.QRect(140, 10, 521, 80))
        font = QtGui.QFont()
        font.setFamily("Palatino Linotype")
        font.setPointSize(35)
        font.setBold(True)
        font.setWeight(75)
        self.lbl_title.setFont(font)
        self.lbl_title.setStyleSheet("color: rgb(85, 170, 255);")
        self.lbl_title.setObjectName("lbl_title")
        self.btn_deleteLesson = QtWidgets.QPushButton(AdminMain)
        self.btn_deleteLesson.setGeometry(QtCore.QRect(31, 520, 200, 55))
        font = QtGui.QFont()
        font.setFamily("Palatino Linotype")
        font.setPointSize(18)
        font.setUnderline(True)
        self.btn_deleteLesson.setFont(font)
        self.btn_deleteLesson.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.btn_deleteLesson.setStyleSheet("border: 1px solid black;\n"
"color: rgb(255, 0, 0);")
        self.btn_deleteLesson.setObjectName("btn_deleteLesson")
        self.btn_addLesson = QtWidgets.QPushButton(AdminMain)
        self.btn_addLesson.setGeometry(QtCore.QRect(570, 520, 200, 55))
        font = QtGui.QFont()
        font.setFamily("Palatino Linotype")
        font.setPointSize(18)
        font.setUnderline(True)
        self.btn_addLesson.setFont(font)
        self.btn_addLesson.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.btn_addLesson.setStyleSheet("border: 1px solid black;\n"
"color: rgb(85, 170, 255);")
        self.btn_addLesson.setObjectName("btn_addLesson")
        self.label = QtWidgets.QLabel(AdminMain)
        self.label.setGeometry(QtCore.QRect(210, 90, 371, 81))
        self.label.setObjectName("label")
        self.btn_addNotice = QtWidgets.QPushButton(AdminMain)
        self.btn_addNotice.setGeometry(QtCore.QRect(360, 520, 200, 55))
        font = QtGui.QFont()
        font.setFamily("Palatino Linotype")
        font.setPointSize(18)
        font.setUnderline(True)
        self.btn_addNotice.setFont(font)
        self.btn_addNotice.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.btn_addNotice.setStyleSheet("border: 1px solid black;\n"
"color: rgb(85, 170, 255);")
        self.btn_addNotice.setObjectName("btn_addNotice")
        self.tableWidget = QtWidgets.QTableWidget(AdminMain)
        self.tableWidget.setGeometry(QtCore.QRect(30, 170, 741, 331))
        font = QtGui.QFont()
        font.setFamily("Palatino Linotype")
        font.setPointSize(14)
        self.tableWidget.setFont(font)
        self.tableWidget.setFrameShape(QtWidgets.QFrame.Panel)
        self.tableWidget.setTabKeyNavigation(True)
        self.tableWidget.setAlternatingRowColors(True)
        self.tableWidget.setObjectName("tableWidget")
        self.tableWidget.setColumnCount(0)
        self.tableWidget.setRowCount(0)
        self.tableWidget.horizontalHeader().setVisible(False)
        self.tableWidget.verticalHeader().setVisible(False)

        self.retranslateUi(AdminMain)
        QtCore.QMetaObject.connectSlotsByName(AdminMain)

    def retranslateUi(self, AdminMain):
        _translate = QtCore.QCoreApplication.translate
        AdminMain.setWindowTitle(_translate("AdminMain", "Term Spors Complex"))
        self.lbl_title.setText(_translate("AdminMain", "Admin Main Page"))
        self.btn_deleteLesson.setText(_translate("AdminMain", "Delete Lesson"))
        self.btn_addLesson.setText(_translate("AdminMain", "Add Lesson"))
        self.label.setText(_translate("AdminMain", "Upcoming Class Schedules"))
        self.btn_addNotice.setText(_translate("AdminMain", "Add Notice"))
