# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'UI/ImportantNoticesPageUI.ui'
#
# Created by: PyQt5 UI code generator 5.15.2
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_ImportantNotices(object):
    def setupUi(self, ImportantNotices):
        ImportantNotices.setObjectName("ImportantNotices")
        ImportantNotices.resize(800, 600)
        ImportantNotices.setMinimumSize(QtCore.QSize(800, 600))
        ImportantNotices.setMaximumSize(QtCore.QSize(800, 600))
        font = QtGui.QFont()
        font.setFamily("Palatino Linotype")
        font.setPointSize(21)
        ImportantNotices.setFont(font)
        self.lbl_title = QtWidgets.QLabel(ImportantNotices)
        self.lbl_title.setGeometry(QtCore.QRect(150, 10, 491, 80))
        font = QtGui.QFont()
        font.setFamily("Palatino Linotype")
        font.setPointSize(35)
        font.setBold(True)
        font.setWeight(75)
        self.lbl_title.setFont(font)
        self.lbl_title.setStyleSheet("color: rgb(85, 170, 255);")
        self.lbl_title.setObjectName("lbl_title")
        self.btn_back = QtWidgets.QPushButton(ImportantNotices)
        self.btn_back.setGeometry(QtCore.QRect(590, 525, 180, 50))
        font = QtGui.QFont()
        font.setFamily("Palatino Linotype")
        font.setPointSize(16)
        font.setUnderline(False)
        self.btn_back.setFont(font)
        self.btn_back.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.btn_back.setStyleSheet("QPushButton{\n"
"    border: 2px solid #9E9E9E;\n"
"    border-radius: 15px;\n"
"    background-color: #00000000;\n"
"    color: #9E9E9E;\n"
"}\n"
"QPushButton:hover{\n"
"    color: #FFFFFF;\n"
"    background-color: #5a5a5a;\n"
"}\n"
"QPushButton:pressed{\n"
"    color: #9c2219;\n"
"}\n"
"QPushButton:checked{\n"
"    color: #2c998e;\n"
"}")
        self.btn_back.setObjectName("btn_back")
        self.tableWidget = QtWidgets.QTableWidget(ImportantNotices)
        self.tableWidget.setGeometry(QtCore.QRect(30, 110, 741, 391))
        font = QtGui.QFont()
        font.setFamily("Palatino Linotype")
        font.setPointSize(14)
        self.tableWidget.setFont(font)
        self.tableWidget.setFrameShape(QtWidgets.QFrame.Panel)
        self.tableWidget.setTabKeyNavigation(True)
        self.tableWidget.setAlternatingRowColors(True)
        self.tableWidget.setObjectName("tableWidget")
        self.tableWidget.setColumnCount(0)
        self.tableWidget.setRowCount(0)
        self.tableWidget.horizontalHeader().setVisible(True)
        self.tableWidget.verticalHeader().setVisible(False)

        self.retranslateUi(ImportantNotices)
        QtCore.QMetaObject.connectSlotsByName(ImportantNotices)

    def retranslateUi(self, ImportantNotices):
        _translate = QtCore.QCoreApplication.translate
        ImportantNotices.setWindowTitle(_translate("ImportantNotices", "Term Spors Complex"))
        self.lbl_title.setText(_translate("ImportantNotices", "Important Notices"))
        self.btn_back.setText(_translate("ImportantNotices", "Back"))
