# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'UI/MainPageUI.ui'
#
# Created by: PyQt5 UI code generator 5.15.2
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Main(object):
    def setupUi(self, Main):
        Main.setObjectName("Main")
        Main.setEnabled(True)
        Main.resize(800, 600)
        Main.setMinimumSize(QtCore.QSize(800, 600))
        font = QtGui.QFont()
        font.setFamily("Palatino Linotype")
        font.setPointSize(18)
        Main.setFont(font)
        Main.setContextMenuPolicy(QtCore.Qt.DefaultContextMenu)
        Main.setTabShape(QtWidgets.QTabWidget.Rounded)
        self.centralwidget = QtWidgets.QWidget(Main)
        self.centralwidget.setObjectName("centralwidget")
        self.verticalLayoutWidget = QtWidgets.QWidget(self.centralwidget)
        self.verticalLayoutWidget.setGeometry(QtCore.QRect(280, 280, 231, 111))
        self.verticalLayoutWidget.setObjectName("verticalLayoutWidget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.verticalLayoutWidget)
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.btn_admin = QtWidgets.QPushButton(self.verticalLayoutWidget)
        font = QtGui.QFont()
        font.setFamily("Palatino Linotype")
        font.setPointSize(18)
        font.setUnderline(True)
        self.btn_admin.setFont(font)
        self.btn_admin.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.btn_admin.setStyleSheet("border: 1px solid black;\n"
"color: rgb(85, 170, 255);")
        self.btn_admin.setObjectName("btn_admin")
        self.verticalLayout.addWidget(self.btn_admin)
        self.btn_member = QtWidgets.QPushButton(self.verticalLayoutWidget)
        font = QtGui.QFont()
        font.setFamily("Palatino Linotype")
        font.setPointSize(18)
        font.setUnderline(True)
        self.btn_member.setFont(font)
        self.btn_member.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.btn_member.setStyleSheet("border: 1px solid black;\n"
"color: rgb(85, 170, 255);")
        self.btn_member.setObjectName("btn_member")
        self.verticalLayout.addWidget(self.btn_member)
        self.lbl_login = QtWidgets.QLabel(self.centralwidget)
        self.lbl_login.setGeometry(QtCore.QRect(330, 180, 141, 91))
        font = QtGui.QFont()
        font.setFamily("Palatino Linotype")
        font.setPointSize(30)
        self.lbl_login.setFont(font)
        self.lbl_login.setStyleSheet("color: rgb(0, 0, 0);")
        self.lbl_login.setObjectName("lbl_login")
        self.lbl_title = QtWidgets.QLabel(self.centralwidget)
        self.lbl_title.setGeometry(QtCore.QRect(120, 10, 591, 80))
        font = QtGui.QFont()
        font.setFamily("Palatino Linotype")
        font.setPointSize(35)
        font.setBold(True)
        font.setWeight(75)
        self.lbl_title.setFont(font)
        self.lbl_title.setStyleSheet("color: rgb(85, 170, 255);")
        self.lbl_title.setObjectName("lbl_title")
        Main.setCentralWidget(self.centralwidget)
        self.statusbar = QtWidgets.QStatusBar(Main)
        self.statusbar.setObjectName("statusbar")
        Main.setStatusBar(self.statusbar)

        self.retranslateUi(Main)
        QtCore.QMetaObject.connectSlotsByName(Main)

    def retranslateUi(self, Main):
        _translate = QtCore.QCoreApplication.translate
        Main.setWindowTitle(_translate("Main", "Term Spors Complex"))
        self.btn_admin.setText(_translate("Main", "Admin"))
        self.btn_member.setText(_translate("Main", "Member"))
        self.lbl_login.setText(_translate("Main", "Login"))
        self.lbl_title.setText(_translate("Main", "Term Sports Complex"))
