# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'UI/PersonalReportPageUI.ui'
#
# Created by: PyQt5 UI code generator 5.15.2
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_PersonalReport(object):
    def setupUi(self, PersonalReport):
        PersonalReport.setObjectName("PersonalReport")
        PersonalReport.resize(800, 600)
        PersonalReport.setMinimumSize(QtCore.QSize(800, 600))
        PersonalReport.setMaximumSize(QtCore.QSize(800, 600))
        font = QtGui.QFont()
        font.setFamily("Palatino Linotype")
        font.setPointSize(18)
        PersonalReport.setFont(font)
        PersonalReport.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.btn_back = QtWidgets.QPushButton(PersonalReport)
        self.btn_back.setGeometry(QtCore.QRect(590, 525, 180, 50))
        font = QtGui.QFont()
        font.setFamily("Palatino Linotype")
        font.setPointSize(16)
        font.setUnderline(False)
        self.btn_back.setFont(font)
        self.btn_back.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.btn_back.setStyleSheet("QPushButton{\n"
"    border: 2px solid #9E9E9E;\n"
"    border-radius: 15px;\n"
"    background-color: QLinearGradient( x1: 0, y1: 0, x2: 0, y2: 1, stop: 0 #88d, stop: 0.1 #99e, stop: 0.49 #77c, stop: 0.5 #66b, stop: 1 #77c);\n"
"    color: #FFFFFF;\n"
"}\n"
"QPushButton:hover{\n"
"    color: #9E9E9E;\n"
"    background-color: #5a5a5a;\n"
"}\n"
"QPushButton:pressed{\n"
"    color: #9c2219;\n"
"}\n"
"QPushButton:checked{\n"
"    color: #2c998e;\n"
"}")
        self.btn_back.setObjectName("btn_back")
        self.horizontalLayoutWidget = QtWidgets.QWidget(PersonalReport)
        self.horizontalLayoutWidget.setGeometry(QtCore.QRect(110, 100, 591, 399))
        self.horizontalLayoutWidget.setObjectName("horizontalLayoutWidget")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.horizontalLayoutWidget)
        self.horizontalLayout.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout.setSpacing(15)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.verticalLayout = QtWidgets.QVBoxLayout()
        self.verticalLayout.setSpacing(3)
        self.verticalLayout.setObjectName("verticalLayout")
        self.lbl_lastClassAtt = QtWidgets.QLabel(self.horizontalLayoutWidget)
        font = QtGui.QFont()
        font.setFamily("Palatino Linotype")
        font.setPointSize(16)
        font.setBold(True)
        font.setWeight(75)
        self.lbl_lastClassAtt.setFont(font)
        self.lbl_lastClassAtt.setObjectName("lbl_lastClassAtt")
        self.verticalLayout.addWidget(self.lbl_lastClassAtt)
        self.lbl_TotNumOfClsAttThisMonth = QtWidgets.QLabel(self.horizontalLayoutWidget)
        font = QtGui.QFont()
        font.setFamily("Palatino Linotype")
        font.setPointSize(13)
        font.setBold(True)
        font.setWeight(75)
        self.lbl_TotNumOfClsAttThisMonth.setFont(font)
        self.lbl_TotNumOfClsAttThisMonth.setObjectName("lbl_TotNumOfClsAttThisMonth")
        self.verticalLayout.addWidget(self.lbl_TotNumOfClsAttThisMonth)
        self.lbl_totalMonthlyFee = QtWidgets.QLabel(self.horizontalLayoutWidget)
        font = QtGui.QFont()
        font.setFamily("Palatino Linotype")
        font.setPointSize(16)
        font.setBold(True)
        font.setWeight(75)
        self.lbl_totalMonthlyFee.setFont(font)
        self.lbl_totalMonthlyFee.setObjectName("lbl_totalMonthlyFee")
        self.verticalLayout.addWidget(self.lbl_totalMonthlyFee)
        self.lbl_inputHeight = QtWidgets.QLabel(self.horizontalLayoutWidget)
        font = QtGui.QFont()
        font.setFamily("Palatino Linotype")
        font.setPointSize(16)
        font.setBold(True)
        font.setWeight(75)
        self.lbl_inputHeight.setFont(font)
        self.lbl_inputHeight.setObjectName("lbl_inputHeight")
        self.verticalLayout.addWidget(self.lbl_inputHeight)
        self.lbl_inputWeight = QtWidgets.QLabel(self.horizontalLayoutWidget)
        font = QtGui.QFont()
        font.setFamily("Palatino Linotype")
        font.setPointSize(16)
        font.setBold(True)
        font.setWeight(75)
        self.lbl_inputWeight.setFont(font)
        self.lbl_inputWeight.setObjectName("lbl_inputWeight")
        self.verticalLayout.addWidget(self.lbl_inputWeight)
        self.lbl_BMI = QtWidgets.QLabel(self.horizontalLayoutWidget)
        font = QtGui.QFont()
        font.setFamily("Palatino Linotype")
        font.setPointSize(16)
        font.setBold(True)
        font.setWeight(75)
        self.lbl_BMI.setFont(font)
        self.lbl_BMI.setObjectName("lbl_BMI")
        self.verticalLayout.addWidget(self.lbl_BMI)
        self.lbl_targetBMI = QtWidgets.QLabel(self.horizontalLayoutWidget)
        font = QtGui.QFont()
        font.setFamily("MS Shell Dlg 2")
        font.setPointSize(16)
        font.setBold(True)
        font.setWeight(75)
        self.lbl_targetBMI.setFont(font)
        self.lbl_targetBMI.setStyleSheet("color: rgb(170, 0, 0);")
        self.lbl_targetBMI.setObjectName("lbl_targetBMI")
        self.verticalLayout.addWidget(self.lbl_targetBMI)
        self.horizontalLayout.addLayout(self.verticalLayout)
        self.verticalLayout_2 = QtWidgets.QVBoxLayout()
        self.verticalLayout_2.setContentsMargins(-1, 5, -1, -1)
        self.verticalLayout_2.setSpacing(8)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.txt_lastClassAtt = QtWidgets.QLineEdit(self.horizontalLayoutWidget)
        font = QtGui.QFont()
        font.setFamily("Palatino Linotype")
        font.setPointSize(18)
        self.txt_lastClassAtt.setFont(font)
        self.txt_lastClassAtt.setStyleSheet("QLineEdit {\n"
"padding: 1px;\n"
"border-style: solid;\n"
"border: 2px solid gray;\n"
"border-radius: 8px;\n"
"}")
        self.txt_lastClassAtt.setObjectName("txt_lastClassAtt")
        self.verticalLayout_2.addWidget(self.txt_lastClassAtt)
        self.txt_TotNumOfClsAttThisMonth = QtWidgets.QLineEdit(self.horizontalLayoutWidget)
        font = QtGui.QFont()
        font.setFamily("Palatino Linotype")
        font.setPointSize(18)
        self.txt_TotNumOfClsAttThisMonth.setFont(font)
        self.txt_TotNumOfClsAttThisMonth.setStyleSheet("QLineEdit {\n"
"padding: 1px;\n"
"border-style: solid;\n"
"border: 2px solid gray;\n"
"border-radius: 8px;\n"
"}")
        self.txt_TotNumOfClsAttThisMonth.setObjectName("txt_TotNumOfClsAttThisMonth")
        self.verticalLayout_2.addWidget(self.txt_TotNumOfClsAttThisMonth)
        self.txt_totalMonthlyFee = QtWidgets.QLineEdit(self.horizontalLayoutWidget)
        font = QtGui.QFont()
        font.setFamily("Palatino Linotype")
        font.setPointSize(18)
        self.txt_totalMonthlyFee.setFont(font)
        self.txt_totalMonthlyFee.setStyleSheet("QLineEdit {\n"
"padding: 1px;\n"
"border-style: solid;\n"
"border: 2px solid gray;\n"
"border-radius: 8px;\n"
"}")
        self.txt_totalMonthlyFee.setObjectName("txt_totalMonthlyFee")
        self.verticalLayout_2.addWidget(self.txt_totalMonthlyFee)
        self.txt_inputHeight = QtWidgets.QLineEdit(self.horizontalLayoutWidget)
        font = QtGui.QFont()
        font.setFamily("Palatino Linotype")
        font.setPointSize(18)
        self.txt_inputHeight.setFont(font)
        self.txt_inputHeight.setStyleSheet("QLineEdit {\n"
"padding: 1px;\n"
"border-style: solid;\n"
"border: 2px solid gray;\n"
"border-radius: 8px;\n"
"}")
        self.txt_inputHeight.setObjectName("txt_inputHeight")
        self.verticalLayout_2.addWidget(self.txt_inputHeight)
        self.txt_inputWeight = QtWidgets.QLineEdit(self.horizontalLayoutWidget)
        font = QtGui.QFont()
        font.setFamily("Palatino Linotype")
        font.setPointSize(18)
        self.txt_inputWeight.setFont(font)
        self.txt_inputWeight.setStyleSheet("QLineEdit {\n"
"padding: 1px;\n"
"border-style: solid;\n"
"border: 2px solid gray;\n"
"border-radius: 8px;\n"
"}")
        self.txt_inputWeight.setObjectName("txt_inputWeight")
        self.verticalLayout_2.addWidget(self.txt_inputWeight)
        self.txt_BMI = QtWidgets.QLineEdit(self.horizontalLayoutWidget)
        font = QtGui.QFont()
        font.setFamily("Palatino Linotype")
        font.setPointSize(18)
        self.txt_BMI.setFont(font)
        self.txt_BMI.setStyleSheet("QLineEdit {\n"
"padding: 1px;\n"
"border-style: solid;\n"
"border: 2px solid gray;\n"
"border-radius: 8px;\n"
"}")
        self.txt_BMI.setObjectName("txt_BMI")
        self.verticalLayout_2.addWidget(self.txt_BMI)
        self.txt_targetBMI = QtWidgets.QLineEdit(self.horizontalLayoutWidget)
        font = QtGui.QFont()
        font.setFamily("Palatino Linotype")
        font.setPointSize(18)
        self.txt_targetBMI.setFont(font)
        self.txt_targetBMI.setStyleSheet("QLineEdit {\n"
"padding: 1px;\n"
"border-style: solid;\n"
"border: 2px solid gray;\n"
"border-radius: 8px;\n"
"}")
        self.txt_targetBMI.setObjectName("txt_targetBMI")
        self.verticalLayout_2.addWidget(self.txt_targetBMI)
        self.horizontalLayout.addLayout(self.verticalLayout_2)
        self.lbl_title = QtWidgets.QLabel(PersonalReport)
        self.lbl_title.setGeometry(QtCore.QRect(190, 10, 421, 80))
        font = QtGui.QFont()
        font.setFamily("Palatino Linotype")
        font.setPointSize(35)
        font.setBold(True)
        font.setWeight(75)
        self.lbl_title.setFont(font)
        self.lbl_title.setStyleSheet("color: #9E9E9E;")
        self.lbl_title.setObjectName("lbl_title")

        self.retranslateUi(PersonalReport)
        QtCore.QMetaObject.connectSlotsByName(PersonalReport)

    def retranslateUi(self, PersonalReport):
        _translate = QtCore.QCoreApplication.translate
        PersonalReport.setWindowTitle(_translate("PersonalReport", "Term Spors Complex"))
        self.btn_back.setText(_translate("PersonalReport", "Back"))
        self.lbl_lastClassAtt.setText(_translate("PersonalReport", "Last class attended:"))
        self.lbl_TotNumOfClsAttThisMonth.setText(_translate("PersonalReport", "Total number of classes\n"
"attended this month:"))
        self.lbl_totalMonthlyFee.setText(_translate("PersonalReport", "Total monthly fee:"))
        self.lbl_inputHeight.setText(_translate("PersonalReport", "Input Height:"))
        self.lbl_inputWeight.setText(_translate("PersonalReport", "Input Weight:"))
        self.lbl_BMI.setText(_translate("PersonalReport", "BMI:"))
        self.lbl_targetBMI.setText(_translate("PersonalReport", "Target BMI:"))
        self.lbl_title.setText(_translate("PersonalReport", "Personal Report"))
