# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'UI/AddLessonPageUI.ui'
#
# Created by: PyQt5 UI code generator 5.15.2
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_AddLesson(object):
    def setupUi(self, AddLesson):
        AddLesson.setObjectName("AddLesson")
        AddLesson.resize(800, 600)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(AddLesson.sizePolicy().hasHeightForWidth())
        AddLesson.setSizePolicy(sizePolicy)
        AddLesson.setMinimumSize(QtCore.QSize(800, 600))
        AddLesson.setMaximumSize(QtCore.QSize(800, 600))
        font = QtGui.QFont()
        font.setFamily("Palatino Linotype")
        font.setPointSize(18)
        AddLesson.setFont(font)
        AddLesson.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.btn_back = QtWidgets.QPushButton(AddLesson)
        self.btn_back.setGeometry(QtCore.QRect(400, 525, 180, 50))
        font = QtGui.QFont()
        font.setFamily("Palatino Linotype")
        font.setPointSize(16)
        font.setUnderline(False)
        self.btn_back.setFont(font)
        self.btn_back.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.btn_back.setStyleSheet("QPushButton{\n"
"    border: 2px solid #9E9E9E;\n"
"    border-radius: 15px;\n"
"    background-color: QLinearGradient( x1: 0, y1: 0, x2: 0, y2: 1, stop: 0 #88d, stop: 0.1 #99e, stop: 0.49 #77c, stop: 0.5 #66b, stop: 1 #77c);\n"
"    color: #FFFFFF;\n"
"}\n"
"QPushButton:hover{\n"
"    color: #9E9E9E;\n"
"    background-color: #5a5a5a;\n"
"}\n"
"QPushButton:pressed{\n"
"    color: #9c2219;\n"
"}\n"
"QPushButton:checked{\n"
"    color: #2c998e;\n"
"}")
        self.btn_back.setObjectName("btn_back")
        self.btn_addLesson = QtWidgets.QPushButton(AddLesson)
        self.btn_addLesson.setGeometry(QtCore.QRect(590, 525, 180, 50))
        font = QtGui.QFont()
        font.setFamily("Palatino Linotype")
        font.setPointSize(16)
        font.setUnderline(False)
        self.btn_addLesson.setFont(font)
        self.btn_addLesson.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.btn_addLesson.setStyleSheet("QPushButton{\n"
"    border: 2px solid #9E9E9E;\n"
"    border-radius: 15px;\n"
"    background-color: QLinearGradient( x1: 0, y1: 0, x2: 0, y2: 1, stop: 0 #88d, stop: 0.1 #99e, stop: 0.49 #77c, stop: 0.5 #66b, stop: 1 #77c);\n"
"    color: #FFFFFF;\n"
"}\n"
"QPushButton:hover{\n"
"    color: #9E9E9E;\n"
"    background-color: #5a5a5a;\n"
"}\n"
"QPushButton:pressed{\n"
"    color: #9c2219;\n"
"}\n"
"QPushButton:checked{\n"
"    color: #2c998e;\n"
"}")
        self.btn_addLesson.setObjectName("btn_addLesson")
        self.horizontalLayoutWidget = QtWidgets.QWidget(AddLesson)
        self.horizontalLayoutWidget.setGeometry(QtCore.QRect(110, 120, 581, 357))
        self.horizontalLayoutWidget.setObjectName("horizontalLayoutWidget")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.horizontalLayoutWidget)
        self.horizontalLayout.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout.setSpacing(15)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.verticalLayout = QtWidgets.QVBoxLayout()
        self.verticalLayout.setObjectName("verticalLayout")
        self.lbl_lessonType = QtWidgets.QLabel(self.horizontalLayoutWidget)
        font = QtGui.QFont()
        font.setFamily("Palatino Linotype")
        font.setPointSize(16)
        font.setBold(True)
        font.setWeight(75)
        self.lbl_lessonType.setFont(font)
        self.lbl_lessonType.setObjectName("lbl_lessonType")
        self.verticalLayout.addWidget(self.lbl_lessonType)
        self.lbl_teacher = QtWidgets.QLabel(self.horizontalLayoutWidget)
        font = QtGui.QFont()
        font.setFamily("Palatino Linotype")
        font.setPointSize(16)
        font.setBold(True)
        font.setWeight(75)
        self.lbl_teacher.setFont(font)
        self.lbl_teacher.setObjectName("lbl_teacher")
        self.verticalLayout.addWidget(self.lbl_teacher)
        self.lbl_date = QtWidgets.QLabel(self.horizontalLayoutWidget)
        font = QtGui.QFont()
        font.setFamily("Palatino Linotype")
        font.setPointSize(16)
        font.setBold(True)
        font.setWeight(75)
        self.lbl_date.setFont(font)
        self.lbl_date.setObjectName("lbl_date")
        self.verticalLayout.addWidget(self.lbl_date)
        self.lbl_time = QtWidgets.QLabel(self.horizontalLayoutWidget)
        font = QtGui.QFont()
        font.setFamily("Palatino Linotype")
        font.setPointSize(16)
        font.setBold(True)
        font.setWeight(75)
        self.lbl_time.setFont(font)
        self.lbl_time.setObjectName("lbl_time")
        self.verticalLayout.addWidget(self.lbl_time)
        self.lbl_price = QtWidgets.QLabel(self.horizontalLayoutWidget)
        font = QtGui.QFont()
        font.setFamily("Palatino Linotype")
        font.setPointSize(16)
        font.setBold(True)
        font.setWeight(75)
        self.lbl_price.setFont(font)
        self.lbl_price.setObjectName("lbl_price")
        self.verticalLayout.addWidget(self.lbl_price)
        self.lbl_description = QtWidgets.QLabel(self.horizontalLayoutWidget)
        font = QtGui.QFont()
        font.setFamily("Palatino Linotype")
        font.setPointSize(16)
        font.setBold(True)
        font.setWeight(75)
        self.lbl_description.setFont(font)
        self.lbl_description.setObjectName("lbl_description")
        self.verticalLayout.addWidget(self.lbl_description)
        self.horizontalLayout.addLayout(self.verticalLayout)
        self.verticalLayout_2 = QtWidgets.QVBoxLayout()
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.txt_lessonType = QtWidgets.QLineEdit(self.horizontalLayoutWidget)
        font = QtGui.QFont()
        font.setFamily("Palatino Linotype")
        font.setPointSize(18)
        self.txt_lessonType.setFont(font)
        self.txt_lessonType.setStyleSheet("QLineEdit {\n"
"padding: 1px;\n"
"border-style: solid;\n"
"border: 2px solid gray;\n"
"border-radius: 8px;\n"
"}")
        self.txt_lessonType.setClearButtonEnabled(True)
        self.txt_lessonType.setObjectName("txt_lessonType")
        self.verticalLayout_2.addWidget(self.txt_lessonType)
        self.txt_teacher = QtWidgets.QLineEdit(self.horizontalLayoutWidget)
        font = QtGui.QFont()
        font.setFamily("Palatino Linotype")
        font.setPointSize(18)
        self.txt_teacher.setFont(font)
        self.txt_teacher.setStyleSheet("QLineEdit {\n"
"padding: 1px;\n"
"border-style: solid;\n"
"border: 2px solid gray;\n"
"border-radius: 8px;\n"
"}")
        self.txt_teacher.setClearButtonEnabled(True)
        self.txt_teacher.setObjectName("txt_teacher")
        self.verticalLayout_2.addWidget(self.txt_teacher)
        self.txt_date = QtWidgets.QDateEdit(self.horizontalLayoutWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.txt_date.sizePolicy().hasHeightForWidth())
        self.txt_date.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily("Palatino Linotype")
        font.setPointSize(18)
        self.txt_date.setFont(font)
        self.txt_date.setCursor(QtGui.QCursor(QtCore.Qt.ArrowCursor))
        self.txt_date.setStyleSheet("QDateEdit {\n"
"padding: 1px;\n"
"border-style: solid;\n"
"border: 2px solid gray;\n"
"border-radius: 8px;\n"
"}\n"
"\n"
"QDateEdit::drop-down {\n"
"background-color: QLinearGradient( x1: 0, y1: 0, x2: 0, y2: 1, stop: 0 #88d, stop: 0.1 #99e, stop: 0.49 #77c, stop: 0.5 #66b, stop: 1 #77c);\n"
"width:25px;\n"
"border: 1px solid gray;\n"
"}\n"
"\n"
"QCalendarWidget QToolButton {\n"
"      height: 55px;\n"
"      width: 100px;\n"
"      color: white;\n"
"      font-size: 16px;\n"
"      icon-size: 28px, 28px;\n"
"      background-color: qlineargradient(x1:0, y1:0, x2:0, y2:1, stop: 0 #cccccc, stop: 1 #333333);\n"
"  }\n"
"  QCalendarWidget QMenu {\n"
"      width: 100px;\n"
"      left: 20px;\n"
"      color: white;\n"
"      font-size: 16px;\n"
"      background-color: rgb(100, 100, 200);\n"
"  }\n"
"  QCalendarWidget QSpinBox { \n"
"      width: 100px; \n"
"      font-size:16px; \n"
"      color: white; \n"
"      background-color: qlineargradient(x1:0, y1:0, x2:0, y2:1, stop: 0 #cccccc, stop: 1 #333333); \n"
"      selection-background-color: rgb(136, 136, 136);\n"
"      selection-color: rgb(255, 255, 255);\n"
"  }\n"
"  QCalendarWidget QSpinBox::up-button { subcontrol-origin: border;  subcontrol-position: top right;  width:35px; }\n"
"  QCalendarWidget QSpinBox::down-button {subcontrol-origin: border; subcontrol-position: bottom right;  width:35px;}\n"
"  QCalendarWidget QSpinBox::up-arrow { width:46px;  height:46px; }\n"
"  QCalendarWidget QSpinBox::down-arrow { width:46px;  height:46px; }\n"
"   \n"
"  /* header row */\n"
"  QCalendarWidget QWidget { alternate-background-color: rgb(128, 128, 128); }\n"
"   \n"
"  /* normal days */\n"
"  QCalendarWidget QAbstractItemView:enabled \n"
"  {\n"
"      font-size:16px;  \n"
"      color: rgb(180, 180, 180);  \n"
"      background-color: rgb(235, 235, 235);\n"
"      selection-background-color: rgb(100, 100, 200); \n"
"    selection-color: white; \n"
"  \n"
"  }\n"
"   \n"
"  /* days in other months */\n"
"  /* navigation bar */\n"
"QCalendarWidget QWidget#qt_calendar_navigationbar\n"
"{ \n"
"  background-color: qlineargradient(x1:0, y1:0, x2:0, y2:1, stop: 0 #cccccc, stop: 1 #333333); \n"
"}\n"
"\n"
"QCalendarWidget QAbstractItemView:disabled \n"
"{ \n"
"color: rgb(64, 64, 64); \n"
"}")
        self.txt_date.setAlignment(QtCore.Qt.AlignCenter)
        self.txt_date.setButtonSymbols(QtWidgets.QAbstractSpinBox.UpDownArrows)
        self.txt_date.setDateTime(QtCore.QDateTime(QtCore.QDate(2021, 1, 1), QtCore.QTime(0, 0, 0)))
        self.txt_date.setCalendarPopup(True)
        self.txt_date.setObjectName("txt_date")
        self.verticalLayout_2.addWidget(self.txt_date)
        self.txt_time = QtWidgets.QTimeEdit(self.horizontalLayoutWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.txt_time.sizePolicy().hasHeightForWidth())
        self.txt_time.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily("Palatino Linotype")
        font.setPointSize(18)
        self.txt_time.setFont(font)
        self.txt_time.setStyleSheet("QDateTimeEdit {\n"
"padding: 1px;\n"
"border-style: solid;\n"
"border: 2px solid gray;\n"
"border-radius: 8px;\n"
"}")
        self.txt_time.setFrame(False)
        self.txt_time.setAlignment(QtCore.Qt.AlignCenter)
        self.txt_time.setButtonSymbols(QtWidgets.QAbstractSpinBox.NoButtons)
        self.txt_time.setCalendarPopup(True)
        self.txt_time.setTimeSpec(QtCore.Qt.LocalTime)
        self.txt_time.setObjectName("txt_time")
        self.verticalLayout_2.addWidget(self.txt_time)
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.txt_price = QtWidgets.QLineEdit(self.horizontalLayoutWidget)
        font = QtGui.QFont()
        font.setFamily("Palatino Linotype")
        font.setPointSize(18)
        self.txt_price.setFont(font)
        self.txt_price.setStyleSheet("QLineEdit {\n"
"padding: 1px;\n"
"border-style: solid;\n"
"border: 2px solid gray;\n"
"border-radius: 8px;\n"
"}")
        self.txt_price.setInputMask("")
        self.txt_price.setMaxLength(10)
        self.txt_price.setClearButtonEnabled(True)
        self.txt_price.setObjectName("txt_price")
        self.horizontalLayout_2.addWidget(self.txt_price)
        self.lbl_priceAZN = QtWidgets.QLabel(self.horizontalLayoutWidget)
        font = QtGui.QFont()
        font.setFamily("Palatino Linotype")
        font.setPointSize(18)
        font.setBold(True)
        font.setWeight(75)
        self.lbl_priceAZN.setFont(font)
        self.lbl_priceAZN.setStyleSheet("color: rgb(100, 100, 200);")
        self.lbl_priceAZN.setObjectName("lbl_priceAZN")
        self.horizontalLayout_2.addWidget(self.lbl_priceAZN)
        self.verticalLayout_2.addLayout(self.horizontalLayout_2)
        self.txt_description = QtWidgets.QLineEdit(self.horizontalLayoutWidget)
        font = QtGui.QFont()
        font.setFamily("Palatino Linotype")
        font.setPointSize(18)
        self.txt_description.setFont(font)
        self.txt_description.setStyleSheet("QLineEdit {\n"
"padding: 1px;\n"
"border-style: solid;\n"
"border: 2px solid gray;\n"
"border-radius: 8px;\n"
"}")
        self.txt_description.setClearButtonEnabled(True)
        self.txt_description.setObjectName("txt_description")
        self.verticalLayout_2.addWidget(self.txt_description)
        self.horizontalLayout.addLayout(self.verticalLayout_2)
        self.lbl_title = QtWidgets.QLabel(AddLesson)
        self.lbl_title.setGeometry(QtCore.QRect(240, 10, 361, 80))
        font = QtGui.QFont()
        font.setFamily("Palatino Linotype")
        font.setPointSize(35)
        font.setBold(True)
        font.setWeight(75)
        self.lbl_title.setFont(font)
        self.lbl_title.setStyleSheet("color: #9E9E9E;")
        self.lbl_title.setObjectName("lbl_title")

        self.retranslateUi(AddLesson)
        QtCore.QMetaObject.connectSlotsByName(AddLesson)

    def retranslateUi(self, AddLesson):
        _translate = QtCore.QCoreApplication.translate
        AddLesson.setWindowTitle(_translate("AddLesson", "Term Spors Complex"))
        self.btn_back.setText(_translate("AddLesson", "Back"))
        self.btn_addLesson.setText(_translate("AddLesson", "Add Lesson"))
        self.lbl_lessonType.setText(_translate("AddLesson", "Lesson type:"))
        self.lbl_teacher.setText(_translate("AddLesson", "Teacher:"))
        self.lbl_date.setText(_translate("AddLesson", "Date:"))
        self.lbl_time.setText(_translate("AddLesson", "Time:"))
        self.lbl_price.setText(_translate("AddLesson", "Price:"))
        self.lbl_description.setText(_translate("AddLesson", "Small description: "))
        self.txt_teacher.setPlaceholderText(_translate("AddLesson", "Fullname"))
        self.txt_date.setDisplayFormat(_translate("AddLesson", "d/M/yyyy"))
        self.txt_price.setPlaceholderText(_translate("AddLesson", "Only digits"))
        self.lbl_priceAZN.setText(_translate("AddLesson", "AZN"))
        self.lbl_title.setText(_translate("AddLesson", "Add a Lesson"))
